-fpic is not needed for MinGW, and MinGW32 issues a warning as a result, which breaks gnu-efi compilation due to -Werror: gnu-efi/lib/boxdraw.c:1:0: error: -fpic ignored for target (all code is position independent) [-Werror]
This patch ensures that -fpic is disabled when MinGW is used.

Signed-off-by: Pete Batard <pbatard@users.sf.net>
Signed-off-by: Nigel Croxon <nigel.croxon@hpe.com>